app_name = "Annals"

[server]
# debug 开发模式，release 生产模式
app_mode = "debug"
http_port = ":3000"
jwt_key = "yourKey"


[mysql]
host = "ip"
port = 3306
user = "user"
password = "password"
db_name = "dbname"
