app_name = "Annals"

[server]
# debug 开发模式，release 生产模式
app_mode = "debug"
http_port = ":3000"
jwt_key = "yourKey"


[mysql]
host = "ip"
port = 3306
user = "user"
password = "password"
db_name = "dbname"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = 10  # 秒
enable_sql_log = false  # 是否启用 SQL 日志
